### ISSUE TITLE
Not working on the latest version 

### ISSUE THREAD

**Issue by Yuanjimengmengda** [muzilib/commit-template-idea-plugin#3]
Current version:
![image](https://github.com/muzilib/commit-template-idea-plugin/assets/45007045/df187741-9e69-4511-b98c-2cacbe4adb3f)

commit texts are not applied to the msg box:

![image](https://github.com/muzilib/commit-template-idea-plugin/assets/45007045/71160575-2edc-46bc-9773-bc0b26ae9633)

Nothing here after clicking on the "OK" button:
![image](https://github.com/muzilib/commit-template-idea-plugin/assets/45007045/dd076360-a190-4838-8299-0d6c5f52de1a)

**Comment by muzilib** [comment]
I have reproduced this problem and it will be fixed in the next version
Thanks for your feedback
