### ISSUE TITLE
我想单独设置插件Git Commit Template为中文可以么？

### ISSUE THREAD

**Issue by ilowe110** [muzilib/commit-template-idea-plugin#6]
IntelliJIDEA 整体是英文的   我想单独设置插件Git Commit Template为中文可以么？

**Comment by muzilib** [comment]
在IDEA 插件中下载中文语言包并勾选为启用状态即可
![image](https://github.com/user-attachments/assets/a74d0da2-1eb1-4460-bf04-76544226b284)

若不希望IDEA软件为中文请ji将语言选择为英文
![image](https://github.com/user-attachments/assets/90be3106-de35-4236-9717-40841882d30e)

**Comment by ilowe110** [comment]
可以了，非常感谢
